apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: svc-weatherapp-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-weatherapp-primary
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: svc-weatherapp-primary
        app.kubernetes.io/component: api
        app.kubernetes.io/instance: svc-weatherapp-canary
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/name: svc-weatherapp-primary
        app.kubernetes.io/part-of: weatherappv2
        app.kubernetes.io/version: latest
    spec:
      containers:
      - env:
        - name: DT_CUSTOM_PROP
          value: version=latest revision=1 releasename=weatherappv2-staging-svc-weatherapp
            keptn_project=weatherappv2 keptn_service=svc-weatherapp keptn_stage=staging
            keptn_deployment=primary
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: DEPLOYMENT_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['deployment']
        - name: CONTAINER_IMAGE
          value: docker.io/simonesan/weatherapp:latest
        - name: KEPTN_PROJECT
          value: svc-weatherapp
        - name: KEPTN_STAGE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KEPTN_SERVICE
          value: svc-weatherapp
        - name: UNLEASH_SERVER_URL
          value: http://unleash.unleash-dev/api
        image: docker.io/simonesan/weatherapp:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health
            port: 4200
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        name: svc-weatherapp
        ports:
        - containerPort: 4200
          name: http
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 4200
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 15
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
status: {}
